### ISSUE TITLE
Colliding entity with block crash when creating dimensions

### ISSUE THREAD

**Issue by Cuplex17** [LeraRiemann/ProjectInfinity#44] opened 2024-09-26 23:05 UTC
Crash log here: https://hst.sh/mamareduru

Happens when books with certain text is thrown into the portal. Happens even with ones obtained from the box of infinite books.
To recreate reliably, throw a book with 'qqqq' (no space or line break after) in the contents with title 'q'.

Mods used include: Sodium, Noisium, Arts & Crafts, Blockus and HandCrafted. Game versions 1.21.1.

**Comment by LeraRiemann** [comment] 2024-09-26 23:31
this one eludes me like a fox! i was never able to reproduce it on my machine
the problem is, amidst generating data for the dimension, something breaks and not all data is generated. when time then comes to generate the dimension itself, it is fed incomplete data and crashes the game
i will try qqqq tomorrow to see if it crashes on my machine but my hopes are slim

**Comment by Goshimy** [comment] 2024-10-01 20:12
Joining this, running into a similar crash - 
MC - 1.21.1
Fabric - 1.16.5
Mods - Fabric api 105
            Infinity 1.12.1
            ModMenu 11.0.2

crash reports - 
https://hst.sh/ciyebukucu.properties
https://hst.sh/qecotuqawa.properties
https://hst.sh/eguxumimat.properties - Book was unsigned Banana, caused crashes on 2 new worlds.

Seems pretty random, I tried qqqq myself and it made a dimension. Hopefully this information helps find the issue,

**Comment by LeraRiemann** [comment] 2024-10-02 17:08
update: i am a silly goose and overlooked changes to particle format in 1.21! this was the only reason for which the bug reemerged
fixed in 1.12.2 of the mod, should now work (checked with Banana), reopen if reemerges again ^^
ty all for bringing this to light!

**Comment by Goshimy** [comment] 2024-10-03 01:36
Thank you for looking into this, but I tried with 1.12.2 and 1.12.3, both crash with Banana unsigned books -
The game crashed whilst colliding entity with block
Error: java.lang.IllegalStateException: This registry can't create new holders without value

https://hst.sh/muyaruweya.properties

I will try to make sure I don't have any other files causing issues.

**Comment by Cuplex17** [comment] 2024-10-03 01:46
It also occurs on 1.20.1
Hopefully the fix can be applied to all previous versions if you can. Thanks!

**Comment by LeraRiemann** [comment] 2024-10-03 06:23
the last log provided has an entirely different crash (in terms of cause listed). will investigate

**Comment by LeraRiemann** [comment] 2024-10-03 07:14
actually i know of a possible way to debug this
can you check if after the crash the attempt to open the world results in a "Errors in datapacks, try safe mode" screen?
if it does, the game log for this session (with this screen) will contain valuable debug information
(sorry for asking you to do roundabout things, i'll package better debug code in future versions)

**Comment by Goshimy** [comment] 2024-10-03 14:39
This time it must have been some error on my part, I believe the issue is solved. 

This morning I  did a reinstall to make sure I had no other issues, and I downloaded 1.12.3 again and used that and fabric API only. Reloading the crash world gave the safe option but did load, and when I used the portal it worked for a second before a server crash. Since that was so different I started a new world made banana again and it worked no issue. Spent a while trying random books and easter eggs (debug will be super useful!) and they all worked.

To test even further I started a world with a majority of my mods, which includes tons of biome altering ones, and I am still able to make random dimensions no issue. So again thank you for looking into this, sorry this second issue must have been on my end somehow.

**Comment by LeraRiemann** [comment] 2024-10-03 14:45
the last crash report you provided listed infinite dimensions' version 1.12.1 so most probably you just haven't actually updated the version accidentially?

as for fixing the crash on 1.20... i think i will eventually backport changes and fixes from .12.х of the mod and further into 1.20 and make a proper _release_ of the mod for 1.20, but that will be a story for another day

**Closed** 2024-10-03 14:45 UTC
