### ISSUE TITLE
Error Message upon launch for 1.20.1

### ISSUE THREAD

**Issue by ZenMakR** [LeraRiemann/ProjectInfinity#34] opened 2024-06-23 14:39 UTC
Hello! When I attempt to launch the mod with 1.20.1, with no other mods (besides Fabric API), I get this error message

I'm not familiar with code so I don't know what this means or why I receive this message.

Edit: Realized I gave like zero information here so allow me to try again.
Ive been reading other issues to see if my problem resides there and I havent found anything. I am unable to even open the game without it crashing and it claims to have something to do with "Infinity" (Unsure if this is the mod itself or something in the mod folder). The crash report is listed below

Crash Message:
![image](https://github.com/LeraRiemann/ProjectInfinity/assets/64114938/61192549-4490-4fe1-a06c-6db4f9516a17)

Crash Report:
https://pastebin.com/F1pAy9sC

**Comment by LeraRiemann** [comment] 2024-06-23 15:57
most probably it is caused by one of the recent pull requests.
can you please test if the previous mod version (a.k.a. 1.10.4-1.20.1) also crashes?

**Comment by shrimp-alfredo** [comment] 2024-06-23 17:53
similar issue on modrinth except modrinth doesnt give me any crash details it just closes and says it crashed

**Comment by ZenMakR** [comment] 2024-06-23 21:27
> most probably it is caused by one of the recent pull requests. can you please test if the previous mod version (a.k.a. 1.10.4-1.20.1) also crashes?

I tested the top 5 versions, and i got the same exact message for all of them.

**Comment by ZenMakR** [comment] 2024-06-23 21:44
> most probably it is caused by one of the recent pull requests. can you please test if the previous mod version (a.k.a. 1.10.4-1.20.1) also crashes?

It seems to crash on 1.10.5 and 1.10.4 but 1.10.3 is working fine

**Comment by cassiancc** [comment] 2024-06-28 14:16
This should now be fixed in the latest version (currently 1.10.8).

**Closed** 2024-09-30 20:27 UTC
